site_name: "LinkML-OWL"
theme:
  name: readthedocs
  analytics:
    gtag: G-2SYBSJVZ23
nav:
  - Introduction:
      What is it?: index.md
      Usage: usage.md
      Basics: basics.md
      Templates: templates.md
      Auto-filling: autofilling.md
  - Examples:
      Showcase: examples.md
      Use in other projects: current-uses.md
  - Tutorial (in progress):
      About: tutorial/index.md
      Part 1 Basics: tutorial/pizza01.md
      Part 2 Relationships: tutorial/pizza02.md
      Part 3 Individuals: tutorial/pizza03.md
      Part 4 Inheritance: tutorial/pizza04.md
#      Part 5: tutorial/pizza05.md
#      Part 6: tutorial/pizza06.md
#      Part 7: tutorial/pizza07.md
#      Part 8: tutorial/pizza08.md
#      Part 9: tutorial/pizza09.md
#      Part 10: tutorial/pizza10.md
  - Futher Info:
      Tips: tips.md
      Comparison with other frameworks: comparison.md
      Further reading: further-reading.md
  - Reference:
      Mappings: mappings.md
      Specification: specification.md
site_url: https://linkml.github.io/linkml-owl/
repo_url: https://github.com/linkml/linkml-owl/
edit_uri: ./edit/main/docs/
